_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
        visualize:
            hammer_telemetry_data.csv_plot:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: hammer_telemetry_data.csv_plot
                        xname: timestamp_epoch_s
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: hammer_telemetry_data.csv_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            neuron_lif_analogy_data.csv_plot:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: neuron_lif_analogy_data.csv_plot
                        xname: timestamp_epoch_s
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: neuron_lif_analogy_data.csv_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            spec_havoc_telemetry_data.csv_plot:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: spec_havoc_telemetry_data.csv_plot
                        xname: timestamp_epoch_s
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: spec_havoc_telemetry_data.csv_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
date:
    value: "20250514"
